name: Windows Build
# コードがmainにpushされた時とpullreqが飛んできた時に自動で実行し手動でも実行できるようにする
  
on:
  push:
    branches: main
  pull_request: 
    branches: main
  workflow_dispatch: {}

# 連続して実行されたときに一つ前の実行中のジョブが停止されるようにする
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  unity-Build:
    name: Run the unity build steps
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./UnityProject
        unityVersion:
        # Unityプロジェクトの現バージョンを指定してください。
          - 2022.3.22f1

    steps:
      # Actionsがリポジトリにアクセスできるようにする
      - name: Checkout
        uses: actions/checkout@v4
      
      # LibraryをCacheしてBuildを高速化する
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      # WindowsBuildする
      - name: Run the Windows build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          buildName: GithubActionsBuildSample

      # Build成果物をアップロードする
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
